# Generated by Django 5.0.3 on 2024-04-01 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=45)),
                ("username", models.CharField(max_length=45, unique=True)),
                ("password", models.CharField(max_length=45)),
                ("bio", models.CharField(blank=True, max_length=255)),
                ("profile_picture_id", models.IntegerField()),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="Follower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "followee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to="users.user",
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "follower",
                "unique_together": {("follower", "followee")},
            },
        ),
    ]
