# Generated by Django 4.2.2 on 2024-04-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                default="instagram_backend/default_profile_picture.jpg",
                upload_to="profile_pictures/",
            ),
        ),
    ]
