# Generated by Django 5.0.3 on 2024-04-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                default="/static/images/default_profile_picture.jpg",
                upload_to="profile_pictures/",
            ),
        ),
    ]
